"""Obsidian App configuration"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_commons.ipynb.

# %% auto 0
__all__ = ['config', 'MountPaths']

# %% ../nbs/04_commons.ipynb 3
from .settings import ObsidianConfig
from enum import Enum
import urllib

# %% ../nbs/04_commons.ipynb 4
config = ObsidianConfig(); config
# (config.PORTAL/'index.qmd').exists()

# %% ../nbs/04_commons.ipynb 5
class MountPaths(Enum):
    gradio_url = config.PREFIX + "_gradio"
    open = "/open"
    tag = "/tag"
    embed="/embed"
    obsidian_url = "obsidian://open"
    edit = "/edit"

    def get_mount_name(self):
        return self.value.rsplit("/")[-1]

    def get_app_url(self):
        return f"{config.PREFIX}{self.value}"

    def to(self, **kwargs):
        if kwargs: return self.get_app_url().rstrip("/")+"?"+"&".join([ f"{k}={urllib.parse.quote(str(v))}" for k,v in kwargs.items()])
        else: return self.get_app_url()

    def with_qparams(self, **kwargs):
        if kwargs: return self.value.rstrip("/")+"?"+"&".join([ f"{k}={urllib.parse.quote(str(v))}" for k,v in kwargs.items()])
        else: return self.value
