"""Embedding with host app"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_plugin.ipynb.

# %% auto 0
__all__ = ['prefix', 'mount_apps', 'get_nav_items']

# %% ../nbs/02_plugin.ipynb 4
from fasthtml.common import *
from monsterui.all import *
from .core import app
from memexplatform.pluginspec import hookimpl
from memexplatform.ui.structure import  add_prefix_to_routes
from .commons import config, MountPaths

# %% ../nbs/02_plugin.ipynb 5
prefix = config.PREFIX

@hookimpl
def mount_apps():
    return (prefix, app, "obsidian")

@hookimpl
def get_nav_items():
    nav_dict = {
        "Discover": [
            ("Obsidian", '/'),
        ],
    }
    return add_prefix_to_routes(nav_dict, prefix)
