"""Embedding with host app"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_plugin.ipynb.

# %% auto 0
__all__ = ['obsidian_fldrs', 'prefix', 'mount_apps', 'get_nav_items']

# %% ../nbs/02_plugin.ipynb 4
from fasthtml.common import *
from monsterui.all import *
from .core import app
from memexplatform.pluginspec import hookimpl
from memexplatform.ui.structure import  add_prefix_to_routes
from .commons import config, MountPaths
from .mdmanager import get_subdirs
from .commons import MountPaths

# %% ../nbs/02_plugin.ipynb 6
obsidian_fldrs = [(p.name.capitalize(), MountPaths.open.to(file=str(p.relative_to(config.OBSIDIAN_VAULT)))) 
for p in get_subdirs(config.OBSIDIAN_VAULT)]; obsidian_fldrs


# %% ../nbs/02_plugin.ipynb 7
prefix = config.PREFIX

@hookimpl
def mount_apps():
    return (prefix, app, "obsidian")

@hookimpl
def get_nav_items():
    nav_dict = {
        "Obsidian": [
            ("Home", config.PREFIX),
        ]+obsidian_fldrs,
    }
    return nav_dict
