"""Embedding with host app"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_plugin.ipynb.

# %% auto 0
__all__ = ['obsidian_fldrs', 'prefix', 'get_obsidian_fldrs', 'EditComponent', 'BacklinkComponent', 'mount_apps', 'get_nav_items',
           'get_toolbar_items']

# %% ../nbs/02_plugin.ipynb 4
from fasthtml.common import *
from monsterui.all import *
from .core import app
from memexplatform.pluginspec import hookimpl
from memexplatform.ui.structure import  add_prefix_to_routes
from .commons import config, MountPaths
from .mdmanager import get_subdirs
from .commons import MountPaths
from .datastore import FileStore, DBStore
import pathlib

# %% ../nbs/02_plugin.ipynb 7
def get_obsidian_fldrs(config):

    store = DBStore(config) if config.ENABLE_DB_MODE else FileStore(config)
    # print(store.subdirs)
    obsidian_fldrs = [(p.name.capitalize(), 
    MountPaths.open.to(file=str(pathlib.Path(p).relative_to(config.OBSIDIAN_VAULT)))) 
    for p in store.subdirs]; obsidian_fldrs
    return obsidian_fldrs

# %% ../nbs/02_plugin.ipynb 8
obsidian_fldrs = get_obsidian_fldrs(config); obsidian_fldrs

# %% ../nbs/02_plugin.ipynb 9
def EditComponent():
    return A(UkIcon('square-pen' ), cls="btn", id='obsidian-button', href=MountPaths.edit.to()),

# %% ../nbs/02_plugin.ipynb 11
def BacklinkComponent():
    return Div(
        Hidden(id='current-lockey', value="", name='current-lockey'),
        Input(id='backlink-drawer', type='checkbox', cls='drawer-toggle'),
        Div(
            Label(UkIcon('link'), fr='backlink-drawer', cls='drawer-button btn'),
            cls='drawer-content'
        ),
        Div(
            Label(fr='backlink-drawer', aria_label='close sidebar', cls='drawer-overlay'),
            Ul(
                Li('Backlinks'), 
                id='backlink_list', 
                cls='menu bg-base-200 text-base-content min-h-full w-80 p-4',
                # hx_post=MountPaths.backlinks.to(),
                # hx_include='#current-lockey',
                # hx_target='#backlink_list',
                # hx_swap='innerHTML',
                # hx_trigger='load, click',
                # hx_boost='false'
            ),
            id='backlink-drawer-content',
            cls='drawer-side z-50',
        ),
        cls='drawer drawer-end'
    )

# %% ../nbs/02_plugin.ipynb 12
prefix = config.PREFIX

@hookimpl
def mount_apps():
    return (prefix, app, "obsidian")

@hookimpl
def get_nav_items():
    nav_dict = {
        "Obsidian": [
            ("Home", config.PREFIX),
        ]+obsidian_fldrs,
    }
    return nav_dict

@hookimpl
def get_toolbar_items():
    # Return a list of heading components (e.g., buttons, icons, etc.)
    return { 
        MountPaths.open.get_app_url(): [EditComponent(), BacklinkComponent()]
            }
