"""Settings module for Chat"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_settings.ipynb.

# %% auto 0
__all__ = ['ObsidianConfig']

# %% ../nbs/03_settings.ipynb 3
from pydantic import BaseModel, SecretStr, SecretBytes, HttpUrl, AnyHttpUrl, Field, FilePath, IPvAnyAddress, NewPath, DirectoryPath
from typing import Optional, List, AnyStr
from pydantic_settings import BaseSettings, SettingsConfigDict
import pathlib
from pydantic import field_validator
import os

# %% ../nbs/03_settings.ipynb 5
class ObsidianConfig(BaseSettings):
    """MemexPlatform Configuration"""
    model_config = SettingsConfigDict(
        env_prefix="MEMEXPLATFORM_",
        env_parse_none_str="",
    )
    PREFIX: str = "/obsidian"
    OBSIDIAN_VAULT: DirectoryPath = pathlib.Path.home() / "obsidian_vault"
    OBSIDIAN_DB: FilePath|NewPath = pathlib.Path.home() / "obsidian_db" / "memexplatform_obsidian.db"
    ENABLE_DB_MODE:bool = False
