"""Obsidian App Apexchart Rendering support for home"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/09_home.ipynb.

# %% auto 0
__all__ = ['make_card', 'summary', 'homepage']

# %% ../../nbs/09_home.ipynb 2
from fasthtml.common import *
from monsterui.all import *
from .summary import chart_timeseries, get_infocard, get_df, chart_tags
from ..commons import config, ExtensionTypes
from .graph import get_graph

# %% ../../nbs/09_home.ipynb 3
def make_card(c, header='Card'):
    return Card(
        H4(header),
        c
    )

# %% ../../nbs/09_home.ipynb 4
def summary(config):

    df_notes = get_df(config, fldrs=['pages', 'journals'], extensions=ExtensionTypes.TEXTLIKE_EXTS)
    notes = get_infocard(df_notes, header='Notes')

    df_templates = get_df(config, fldrs=['templates'], extensions=ExtensionTypes.TEXTLIKE_EXTS)
    templates = get_infocard(df_templates, header='Templates')

    df_clippings = get_df(config, fldrs=['Clippings'], extensions=ExtensionTypes.TEXTLIKE_EXTS)
    clippings = get_infocard(df_clippings, header='Clippings')

    df_images= get_df(config, fldrs=['pages', 'journals', 'assets'], extensions=ExtensionTypes.IMAGE_EXTS)
    images = get_infocard(df_images, header='Images')

    df_audios= get_df(config, fldrs=['pages', 'journals', 'assets'], extensions=ExtensionTypes.AUDIO_EXTS)
    audios = get_infocard(df_audios, header='Audios')

    df_videos= get_df(config, fldrs=['pages', 'journals', 'assets'], extensions=ExtensionTypes.VIDEO_EXTS)
    videos = get_infocard(df_videos, header='Videos')

    top_row = Grid(*[notes, clippings, templates, images, audios, videos], cols_max=6)
    ts = make_card(chart_timeseries(df_notes), header='History')
    tagbars = make_card(chart_tags(), header='Tags')
    mid_row = Grid(*[ts, tagbars], cols_max=2)
    # 
    return Grid(*[top_row, mid_row], cols_max=1, lg=2)

# %% ../../nbs/09_home.ipynb 5
def homepage(config):
    summary_comp = summary(config)
    graph = Card(
        Iframe(
            srcdoc=get_graph(),
            style="""
                position: absolute;
                top: 0; left: 0;
                width: 100%; height: 80%;
                border: none;
            """
        ),
       style="""
            position: relative; 
            height: calc(100vh - 60px);
            border: none;       /* remove border */
            box-shadow: none;   /* remove shadow if any */
            padding: 0;         /* remove padding */
       """  # Card has fixed viewport height
    )
    comp = Div(
            TabContainer(
                Li(A("Summary",href='#', cls='uk-active')),
                Li(A("Graph",href='#')),
                uk_switcher=f'connect: #tab-obsidian; animation: uk-animation-fade',
                alt=True),
            Ul(id=f"tab-obsidian", cls="uk-switcher")(
                Li(summary_comp),
                Li(graph), # 'customapps.qmd'
            ),
        id="home-obsidian",
    )
    return comp
