"""Obsidian App Apexchart Rendering support"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/08a_engine.apexchat.ipynb.

# %% auto 0
__all__ = ['ApexChartEngine']

# %% ../../nbs/08a_engine.apexchat.ipynb 2
from fasthtml.common import *
from monsterui.all import *
import json

# %% ../../nbs/08a_engine.apexchat.ipynb 4
class ApexChartEngine(object):

    def __init__(self, token):
        self._token = token
        try:
            raw = json.loads(self._token.children[0].content)
        except json.JSONDecodeError:
            return f"<pre><code>{self._token.children[0].content}</code></pre>"

        # If user provides {"cls": "...", "opts": {...}}
        if isinstance(raw, dict) and "opts" in raw:
            self.cls = raw.get("cls", "max-w-md max-h-md")
            self.opts = raw["opts"]
        else:
            # otherwise treat the whole thing as the spec
            self.cls = "max-w-md max-h-md"
            self.opts = raw

    def render_html(self):
        return to_xml(ApexChart(opts=self.opts, cls=self.cls))
